import Head from "next/head";
import Timeline from "@/src/components/Timeline";

export default function Home() {
  return (
    <>
      <Head>
        <title>SNS Udemy</title>
        <meta name="sescription" content="Generated by create next app" />
        <meta name="viewpoint" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        
      <div>
        <Timeline />
      </div>
    </>
  )
}
